# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    # https://github.com/marketplace/actions/cache
    - name: Cache stuff
      id: cache-stuff
      uses: actions/cache@v2
      if: always()
      with:
        path: |
          ./cache
        key: solr882.zip
    # https://github.com/marketplace/actions/setup-java-jdk
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '11'        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: install -d cache
    - run: if ! test -e cache/solr.zip; then wget -O cache/solr.zip https://archive.apache.org/dist/lucene/solr/8.8.2/solr-8.8.2.zip; fi
    - run: cp -fv cache/solr.zip .
    - run: npm install
    - run: npm run ci
    - run: cat solr/server/logs/*
      if: always()

