# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # https://github.com/marketplace/actions/setup-java-jdk
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '11'        
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    # https://github.com/marketplace/actions/cache
    - name: Cache stuff
      id: cache-stuff
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          cache
        key: ${{ runner.os }}-stuff
    - run: install -d cache
    - run: if ! test -e cache/solr.tgz; then wget -O cache/solr.tgz https://archive.apache.org/dist/lucene/solr/7.7.3/solr-7.7.3.tgz; fi
    - run: install -d solr
    - run: tar xzf cache/solr.tgz --strip-components=1 -C solr
    - run: cd solr/bin && ./solr start && sleep 10 && ./solr create_collection -c notes || ls -l
    - run: npm install
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

